{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "AgentTimeEntry",
    "version" : "1.0.0"
  },
  "paths" : {
    "/api/v1/agents/{agentId}/timeEntry" : {
      "get" : {
        "tags" : [ "AgentTimeEntry" ],
        "summary" : "List Agent Time Entries",
        "description" : "This API lists the time entries associated with an agent.",
        "operationId" : "getTimeEntryByAgentId",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "include",
          "in" : "query",
          "description" : "Secondary information related to the time entry. Value supported is owner.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string" ],
            "enum" : [ "owner" ],
            "pattern" : "(owner)",
            "maxLength" : 100
          }
        }, {
          "name" : "module",
          "in" : "query",
          "description" : "Module from which the time entries must be fetched. Values allowed are tickets, tasks, calls and events.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string" ],
            "enum" : [ "tickets", "tasks", "calls", "events" ],
            "maxLength" : 100
          }
        }, {
          "name" : "departmentId",
          "in" : "query",
          "description" : "ID of the department",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "name" : "createdTimeRange",
          "in" : "query",
          "description" : "Key that filters time entries created in a particular period of time. Enter the from and to dates in the ISO date format of yyyy-MM-ddThh:mm:ss.SSSZ; for example, createdTimeRange=2017-11-05T00:00:00.000Z,2018-09-05T23:59:00.000Z.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string" ],
            "maxLength" : 100,
            "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z)),(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))|null"
          }
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "Number of time entries to fetch",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "integer" ],
            "format" : "int32",
            "pattern" : "([0-9]+)",
            "minimum" : 1,
            "maximum" : 100
          }
        }, {
          "name" : "billStatus",
          "in" : "query",
          "description" : "Key that filters time entries, based on their billing status: nonBillable , billable or billed",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string" ],
            "enum" : [ "nonBillable", "billable", "billed" ],
            "maxLength" : 100
          }
        }, {
          "name" : "orderBy",
          "in" : "query",
          "description" : "Key that sorts the time entries in ascending or descending order, based on the executedTime attribute. Values allowed are ASC (default) and DESC.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string" ],
            "enum" : [ "ASC", "DESC" ],
            "maxLength" : 100
          }
        }, {
          "name" : "from",
          "in" : "query",
          "description" : "Index number, starting from which the time entries must be fetched",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "integer" ],
            "format" : "int32",
            "pattern" : "([0-9]+)",
            "default" : 0
          }
        }, {
          "name" : "modifiedTimeRange",
          "in" : "query",
          "description" : "Key that filters time entries whose details were modified in a particular period of time. Enter the from and to dates in the ISO date format of yyyy-MM-ddThh:mm:ss.SSSZ; for example, modifiedTimeRange=2017-11-05T00:00:00.000Z,2018-09-05T23:59:00.000Z.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string" ],
            "maxLength" : 100,
            "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z)),(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))|null"
          }
        }, {
          "name" : "agentId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "204" : {
            "$ref" : "./Common.json#/components/responses/emptyResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/getTimeEntryByAgentIdResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/agents/{agentId}/timeEntrySummation" : {
      "get" : {
        "tags" : [ "AgentTimeEntry" ],
        "summary" : "Get summation of Agent Time Entries",
        "description" : "This API fetches the sum of time entries associated with an agent.",
        "operationId" : "getSummationOfTimeEntryForAgent",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "module",
          "in" : "query",
          "description" : "Module from which the time entries must be fetched. Values allowed are tickets, tasks, calls and events.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string" ],
            "enum" : [ "tickets", "tasks", "calls", "events" ],
            "maxLength" : 100
          }
        }, {
          "name" : "departmentId",
          "in" : "query",
          "description" : "ID of the department",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "name" : "billStatus",
          "in" : "query",
          "description" : "Key that filters time entries, based on their billing status: nonBillable , billable or billed",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string" ],
            "enum" : [ "nonBillable", "billable", "billed" ],
            "maxLength" : 100
          }
        }, {
          "name" : "agentId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/getSummationOfTimeEntryForAgentResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/agents/{agentId}/timeEntry/{agentTimeEntryId}" : {
      "get" : {
        "tags" : [ "AgentTimeEntry" ],
        "summary" : "Get an Agent Time Entry",
        "description" : "This API fetches a time entry related to an agent.",
        "operationId" : "getTimeEntryForAgent",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "include",
          "in" : "query",
          "description" : "Secondary information related to the time entry. Value supported is owner.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string" ],
            "enum" : [ "owner" ],
            "pattern" : "(owner)",
            "maxLength" : 100
          }
        }, {
          "name" : "agentId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "name" : "agentTimeEntryId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "422" : {
            "$ref" : "./Common.json#/components/responses/multipleUnprocessEntityResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/getTimeEntryForAgentResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "getActivityParent" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "ticketNumber" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Ticket number of the associated ticket",
            "format" : "int32",
            "pattern" : "([0-9]+)"
          },
          "associatedTicketId" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the ticket associated with the parent task",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "subject" : {
            "type" : [ "string", "null" ],
            "description" : "Subject of the associated record",
            "maxLength" : 100,
            "minLength" : 0
          },
          "id" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the associated record",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "type" : {
            "type" : [ "string", "null" ],
            "description" : "Module type of the associated record. Possible values: TICKETS, TASKS, CALLS, EVENTS",
            "maxLength" : 100,
            "minLength" : 0
          }
        },
        "required" : [ "associatedTicketId", "id", "subject", "ticketNumber", "type" ]
      },
      "getTimeEntryForAgentResponse" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "executedTime" : {
            "type" : [ "string", "null" ],
            "description" : "Time when work related to the time entry started",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
          },
          "customFields" : {
            "type" : [ "object", "null" ],
            "description" : "User-defined fields related to the time entry",
            "additionalProperties" : false,
            "patternProperties" : {
              "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+" : {
                "type" : [ "string", "null" ],
                "maxLength" : 100,
                "minLength" : 0,
                "pattern" : "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+"
              }
            }
          },
          "departmentId" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the department associated with the time entry",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "agentCostPerHour" : {
            "type" : [ "string", "null" ],
            "description" : "Hourly cost of the agent",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "([0-9]{1,13}(\\.[0-9]*)?)"
          },
          "description" : {
            "type" : [ "string", "null" ],
            "description" : "Description of the time entry",
            "maxLength" : 100,
            "minLength" : 0
          },
          "ownerId" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the user associated with the time entry",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "mode" : {
            "type" : [ "string", "null" ],
            "description" : "Time tracking mode configured for the time entry. Possible values: MANUAL, AUTO",
            "enum" : [ "MANUAL", "AUTO" ]
          },
          "isTrashed" : {
            "type" : [ "boolean", "null" ],
            "description" : "Indicates whether the time entry is in the Recycle Bin. Possible values: true = in the Recycle Bin, false = not in the Recycle Bin"
          },
          "requestId" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the ticket (request) associated with the time entry",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "createdTime" : {
            "type" : [ "string", "null" ],
            "description" : "Time when the time entry was created",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
          },
          "id" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the time entry",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "requestChargeType" : {
            "type" : [ "string", "null" ],
            "description" : "Type of request associated with the time entry. Possible values: Customer Service, Upgrade Request, Product Consultation, Support and Maintenance",
            "enum" : [ "Customer Service", "Upgrade Request", "Product Consultation", "Support and Maintenance", "MANUAL" ]
          },
          "layoutDetails" : {
            "type" : [ "object", "null" ],
            "description" : "Details of the layout associated with the time entry",
            "additionalProperties" : false,
            "maxProperties" : 2,
            "minProperties" : 2,
            "properties" : {
              "id" : {
                "type" : [ "string", "integer", "null" ],
                "description" : "Unique ID of the layout",
                "format" : "int64",
                "pattern" : "([0-9]+)"
              },
              "layoutName" : {
                "type" : [ "string", "null" ],
                "description" : "Name of the layout",
                "maxLength" : 120,
                "minLength" : 0,
                "pattern" : "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+"
              }
            },
            "required" : [ "id", "layoutName" ]
          },
          "secondsSpent" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Number of seconds recorded in the time entry",
            "format" : "int32",
            "pattern" : "([0-9]+)"
          },
          "cf" : {
            "type" : [ "object", "null" ],
            "description" : "User-defined fields related to the time entry",
            "additionalProperties" : false,
            "patternProperties" : {
              "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+" : {
                "type" : [ "string", "null" ],
                "maxLength" : 100,
                "minLength" : 0,
                "pattern" : "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+"
              }
            }
          },
          "fixedCost" : {
            "type" : [ "number", "string", "null" ],
            "description" : "Fixed cost",
            "format" : "double",
            "pattern" : "([0-9]{1,13}(\\.[0-9]*)?)"
          },
          "minutesSpent" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Number of minutes recorded in the time entry",
            "format" : "int32",
            "pattern" : "([0-9]+)"
          },
          "hoursSpent" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Number of hours recorded in the time entry",
            "format" : "int32",
            "pattern" : "([0-9]+)"
          },
          "layoutId" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the layout associated with the time entry",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "isBillable" : {
            "type" : [ "boolean", "null" ],
            "description" : "Indicates whether the time entry is billable. Possible values: true = billable, false = not billable"
          },
          "createdBy" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the user who created the time entry",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "invoiceId" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the invoice related to the time entry",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "additionalCost" : {
            "type" : [ "string", "null" ],
            "description" : "Additional cost incurred for the time entry",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "([0-9]{1,13}(\\.[0-9]*)?)"
          },
          "totalCost" : {
            "type" : [ "string", "null" ],
            "description" : "Total cost incurred for the time entry",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "([0-9]{1,13}(\\.[0-9]*)?)"
          },
          "taskId" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the task associated with the time entry",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "additionalCost", "agentCostPerHour", "cf", "createdBy", "createdTime", "customFields", "departmentId", "description", "executedTime", "fixedCost", "hoursSpent", "id", "invoiceId", "isBillable", "isTrashed", "layoutDetails", "layoutId", "minutesSpent", "mode", "ownerId", "requestChargeType", "requestId", "secondsSpent", "taskId", "totalCost" ]
      },
      "listActivityTimeEntryForAgentResponse" : {
        "type" : [ "object" ],
        "additionalProperties" : false,
        "allOf" : [ {
          "$ref" : "#/components/schemas/getTimeEntryForAgentResponse"
        }, {
          "type" : [ "object", "null" ],
          "properties" : {
            "parent" : {
              "$ref" : "#/components/schemas/getActivityParent"
            },
            "billingType" : {
              "type" : [ "string", "null" ],
              "description" : "Billing type configured for time tracking. Possible values: FIXED_COST_FOR_TICKETS, FIXED_COST_FOR_AGENTS, SPECIFIC_COST_PER_AGENT, SPECIFIC_COST_PER_PROFILE",
              "maxLength" : 100,
              "minLength" : 0
            }
          },
          "required" : [ "billingType", "parent" ],
          "additionalProperties" : false
        } ]
      },
      "getTicketParent" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "ticketNumber" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Ticket number of the associated ticket",
            "format" : "int32",
            "pattern" : "([0-9]+)"
          },
          "subject" : {
            "type" : [ "string", "null" ],
            "description" : "Subject of the associated record",
            "maxLength" : 100,
            "minLength" : 0
          },
          "id" : {
            "type" : [ "string", "integer", "null" ],
            "description" : "Unique ID of the associated record",
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "type" : {
            "type" : [ "string", "null" ],
            "description" : "Module type of the associated record. Possible values: TICKETS, TASKS, CALLS, EVENTS",
            "maxLength" : 100,
            "minLength" : 0
          }
        },
        "required" : [ "id", "subject", "ticketNumber", "type" ]
      },
      "listTicketTimeEntryForAgentResponse" : {
        "type" : [ "object" ],
        "additionalProperties" : false,
        "allOf" : [ {
          "$ref" : "#/components/schemas/getTimeEntryForAgentResponse"
        }, {
          "type" : [ "object", "null" ],
          "properties" : {
            "parent" : {
              "$ref" : "#/components/schemas/getTicketParent"
            },
            "billingType" : {
              "type" : [ "string", "null" ],
              "description" : "Billing type configured for time tracking. Possible values: FIXED_COST_FOR_TICKETS, FIXED_COST_FOR_AGENTS, SPECIFIC_COST_PER_AGENT, SPECIFIC_COST_PER_PROFILE",
              "maxLength" : 100,
              "minLength" : 0
            }
          },
          "required" : [ "billingType", "parent" ],
          "additionalProperties" : false
        } ]
      },
      "data" : {
        "type" : [ "array", "null" ],
        "description" : "List of time entries associated with the agent",
        "items" : {
          "oneOf" : [ {
            "$ref" : "#/components/schemas/listActivityTimeEntryForAgentResponse"
          }, {
            "$ref" : "#/components/schemas/listTicketTimeEntryForAgentResponse"
          } ]
        }
      }
    },
    "responses" : {
      "getTimeEntryByAgentIdResponse" : {
        "description" : "getTimeEntryByAgentIdResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object" ],
              "allOf" : [ {
                "type" : [ "object" ],
                "properties" : {
                  "data" : {
                    "type" : [ "array" ],
                    "description" : "List of time entries associated with the agent",
                    "items" : {
                      "type" : [ "object" ],
                      "properties" : {
                        "owner" : {
                          "type" : [ "object", "null" ],
                          "description" : "Details of the user associated with the time entry",
                          "additionalProperties" : false,
                          "maxProperties" : 5,
                          "minProperties" : 5,
                          "properties" : {
                            "firstName" : {
                              "type" : [ "string", "null" ],
                              "description" : "First name of the user associated with the time entry",
                              "maxLength" : 50,
                              "minLength" : 0
                            },
                            "lastName" : {
                              "type" : [ "string", "null" ],
                              "description" : "Last name of the user associated with the time entry",
                              "maxLength" : 50,
                              "minLength" : 0
                            },
                            "photoURL" : {
                              "type" : [ "string", "null" ],
                              "description" : "URL of the user's profile photo",
                              "maxLength" : 100,
                              "minLength" : 0,
                              "pattern" : "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+"
                            },
                            "name" : {
                              "type" : [ "string", "null" ],
                              "description" : "Display name of the user associated with the time entry",
                              "maxLength" : 50,
                              "minLength" : 0
                            },
                            "id" : {
                              "type" : [ "string", "integer", "null" ],
                              "description" : "Unique ID of the user associated with the time entry",
                              "format" : "int64",
                              "pattern" : "([0-9]+)"
                            }
                          },
                          "required" : [ "firstName", "id", "lastName", "name", "photoURL" ]
                        }
                      },
                      "additionalProperties" : false
                    }
                  }
                },
                "additionalProperties" : false
              }, {
                "type" : [ "object", "null" ],
                "additionalProperties" : false,
                "properties" : {
                  "data" : {
                    "$ref" : "#/components/schemas/data"
                  }
                },
                "required" : [ "data" ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "owner" : {
                      "firstName" : "Oliver",
                      "lastName" : "Miller",
                      "photoURL" : "https://contacts.example.com/file?t=user&ID=1234567890",
                      "name" : "Oliver Miller",
                      "id" : "4000000008688129"
                    },
                    "secondsSpent" : "21",
                    "parent" : {
                      "ticketNumber" : "1001",
                      "associatedTicketId" : "4000000031007",
                      "subject" : "Task subject",
                      "id" : "4000000031010",
                      "type" : [ "TASKS" ]
                    },
                    "executedTime" : 1466627400000,
                    "fixedCost" : null,
                    "departmentId" : "4000000008694",
                    "minutesSpent" : "23",
                    "creatorId" : "4000000008692",
                    "agentCostPerHour" : "3.0",
                    "description" : "Time Entry description",
                    "hoursSpent" : "3",
                    "ownerId" : "4000000008692",
                    "isBillable" : true,
                    "mode" : "MANUAL",
                    "isTrashed" : "false",
                    "billingType" : "FIXED_COST_FOR_TICKETS",
                    "createdTime" : 1466061884000,
                    "invoiceId" : "40000000086881212",
                    "id" : "4000000033001",
                    "requestChargeType" : "Customer Service",
                    "additionalCost" : "10.0",
                    "totalCost" : "20.17"
                  }, {
                    "owner" : {
                      "firstName" : "Oliver",
                      "lastName" : "Miller",
                      "photoURL" : "https://contacts.example.com/file?t=user&ID=1234567890",
                      "name" : "Oliver Miller",
                      "id" : "4000000008688129"
                    },
                    "secondsSpent" : "21",
                    "parent" : {
                      "ticketNumber" : "1001",
                      "associatedTicketId" : "4000000031007",
                      "subject" : "Task subject",
                      "id" : "4000000031010",
                      "type" : [ "TASKS" ]
                    },
                    "executedTime" : 1466796600000,
                    "fixedCost" : null,
                    "departmentId" : "4000000008694",
                    "minutesSpent" : "34",
                    "creatorId" : "4000000008692",
                    "agentCostPerHour" : "10.0",
                    "description" : "Time Entry description",
                    "hoursSpent" : "3",
                    "ownerId" : "4000000012090",
                    "isBillable" : true,
                    "mode" : "MANUAL",
                    "isTrashed" : "false",
                    "billingType" : "FIXED_COST_FOR_TICKETS",
                    "createdTime" : 1466063199000,
                    "invoiceId" : "40000000086881212",
                    "id" : "4000000033006",
                    "requestChargeType" : "Product Consultation",
                    "additionalCost" : "10.0",
                    "totalCost" : "45.72"
                  }, {
                    "owner" : {
                      "firstName" : "Oliver",
                      "lastName" : "Miller",
                      "photoURL" : "https://contacts.example.com/file?t=user&ID=1234567890",
                      "name" : "Oliver Miller",
                      "id" : "4000000008688129"
                    },
                    "secondsSpent" : "22",
                    "parent" : {
                      "ticketNumber" : "1001",
                      "associatedTicketId" : "4000000031007",
                      "subject" : "Task subject",
                      "id" : "4000000031010",
                      "type" : [ "TASKS" ]
                    },
                    "executedTime" : 1465846200000,
                    "fixedCost" : null,
                    "departmentId" : "4000000008694",
                    "minutesSpent" : "22",
                    "creatorId" : "4000000008692",
                    "agentCostPerHour" : "20.0",
                    "description" : "Time Entry description",
                    "hoursSpent" : "32",
                    "ownerId" : "4000000008692",
                    "isBillable" : true,
                    "mode" : "MANUAL",
                    "isTrashed" : "false",
                    "billingType" : "FIXED_COST_FOR_TICKETS",
                    "createdTime" : 1466063392000,
                    "invoiceId" : "40000000086881212",
                    "id" : "4000000033011",
                    "requestChargeType" : "Customer Service",
                    "additionalCost" : "10.0",
                    "totalCost" : "657.46"
                  } ]
                }
              }
            }
          }
        }
      },
      "getSummationOfTimeEntryForAgentResponse" : {
        "description" : "getSummationOfTimeEntryForAgentResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "totalMins" : {
                  "type" : [ "string", "integer", "null" ],
                  "description" : "Total number of minutes across the matched time entries",
                  "format" : "int32",
                  "pattern" : "([0-9]+)"
                },
                "totalHours" : {
                  "type" : [ "string", "integer", "null" ],
                  "description" : "Total number of hours across the matched time entries",
                  "format" : "int32",
                  "pattern" : "([0-9]+)"
                },
                "totalCosts" : {
                  "type" : [ "string", "number", "null" ],
                  "description" : "Total cost across the matched time entries",
                  "pattern" : "([0-9\\.]+)"
                },
                "totalSeconds" : {
                  "type" : [ "string", "integer", "null" ],
                  "description" : "Total number of seconds across the matched time entries",
                  "format" : "int32",
                  "pattern" : "([0-9]+)"
                }
              },
              "required" : [ "totalCosts", "totalHours", "totalMins", "totalSeconds" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "totalMins" : 5,
                  "totalHours" : 12,
                  "totalCosts" : 1000,
                  "totalSeconds" : 24
                }
              }
            }
          }
        }
      },
      "getTimeEntryForAgentResponse" : {
        "description" : "getTimeEntryForAgentResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object" ],
              "allOf" : [ {
                "type" : [ "object" ],
                "properties" : {
                  "owner" : {
                    "type" : [ "object", "null" ],
                    "description" : "Details of the user associated with the time entry",
                    "additionalProperties" : false,
                    "maxProperties" : 5,
                    "minProperties" : 5,
                    "properties" : {
                      "firstName" : {
                        "type" : [ "string", "null" ],
                        "description" : "First name of the user associated with the time entry",
                        "maxLength" : 50,
                        "minLength" : 0
                      },
                      "lastName" : {
                        "type" : [ "string", "null" ],
                        "description" : "Last name of the user associated with the time entry",
                        "maxLength" : 50,
                        "minLength" : 0
                      },
                      "photoURL" : {
                        "type" : [ "string", "null" ],
                        "description" : "URL of the user's profile photo",
                        "maxLength" : 100,
                        "minLength" : 0,
                        "pattern" : "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+"
                      },
                      "name" : {
                        "type" : [ "string", "null" ],
                        "description" : "Display name of the user associated with the time entry",
                        "maxLength" : 50,
                        "minLength" : 0
                      },
                      "id" : {
                        "type" : [ "string", "integer", "null" ],
                        "description" : "Unique ID of the user associated with the time entry",
                        "format" : "int64",
                        "pattern" : "([0-9]+)"
                      }
                    },
                    "required" : [ "firstName", "id", "lastName", "name", "photoURL" ]
                  }
                },
                "additionalProperties" : false
              }, {
                "oneOf" : [ {
                  "type" : [ "object" ],
                  "additionalProperties" : false,
                  "allOf" : [ {
                    "$ref" : "#/components/schemas/getTimeEntryForAgentResponse"
                  }, {
                    "type" : [ "object", "null" ],
                    "properties" : {
                      "parent" : {
                        "$ref" : "#/components/schemas/getTicketParent"
                      }
                    },
                    "required" : [ "parent" ],
                    "additionalProperties" : false
                  } ]
                }, {
                  "type" : [ "object" ],
                  "additionalProperties" : false,
                  "allOf" : [ {
                    "$ref" : "#/components/schemas/getTimeEntryForAgentResponse"
                  }, {
                    "type" : [ "object", "null" ],
                    "properties" : {
                      "parent" : {
                        "$ref" : "#/components/schemas/getActivityParent"
                      }
                    },
                    "required" : [ "parent" ],
                    "additionalProperties" : false
                  } ]
                } ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "owner" : {
                    "firstName" : "Oliver",
                    "lastName" : "Miller",
                    "photoURL" : "https://contacts.example.com/file?t=user&ID=1234567890",
                    "name" : "Oliver Miller",
                    "id" : "4000000008688129"
                  },
                  "secondsSpent" : "21",
                  "parent" : {
                    "ticketNumber" : "1001",
                    "associatedTicketId" : "4000000031007",
                    "subject" : "Task subject",
                    "id" : "4000000031010",
                    "type" : [ "TASKS" ]
                  },
                  "cf" : {
                    "cf_timeentryname" : "time1"
                  },
                  "executedTime" : 1466627400000,
                  "fixedCost" : null,
                  "departmentId" : "4000000008694",
                  "minutesSpent" : "23",
                  "creatorId" : "4000000008692",
                  "agentCostPerHour" : "3.0",
                  "description" : "Time Entry description",
                  "hoursSpent" : "3",
                  "ownerId" : "4000000008692",
                  "isBillable" : true,
                  "mode" : "MANUAL",
                  "isTrashed" : "false",
                  "billingType" : "FIXED_COST_FOR_TICKETS",
                  "createdTime" : 1466061884000,
                  "invoiceId" : "40000000086881212",
                  "id" : "4000000033001",
                  "requestChargeType" : "Customer Service",
                  "additionalCost" : "10.0",
                  "totalCost" : "20.17"
                }
              }
            }
          }
        }
      }
    },
    "securitySchemes" : {
      "cookie-auth" : {
        "$ref" : "./Common.json#/components/securitySchemes/cookie-auth"
      },
      "org-oauth" : {
        "$ref" : "./Common.json#/components/securitySchemes/org-oauth"
      },
      "iam-oauth2-schema" : {
        "$ref" : "./Common.json#/components/securitySchemes/iam-oauth2-schema"
      }
    }
  },
  "x-entity" : "AgentTimeEntry"
}