{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "User",
    "version" : "1.0.0"
  },
  "paths" : {
    "/api/v1/users/{userId}" : {
      "get" : {
        "tags" : [ "User" ],
        "summary" : "Get User Details",
        "description" : "This API fetches the details of a particular help center user.",
        "operationId" : "getUserDetails",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "include",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string" ],
            "enum" : [ "contact" ],
            "maxItems" : 1,
            "pattern" : "(contact)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "Additional information related to the user. Value allowed is @contact@."
        }, {
          "name" : "helpCenterId",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "ID of the help center from which the user must be fetched"
        }, {
          "name" : "userId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/userDetailViewJson"
          },
          "422" : {
            "$ref" : "./Common.json#/components/responses/invalidDataErrorResponse"
          },
          "500" : {
            "$ref" : "./Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "./Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.contacts.READ", "Desk.settings.READ", "Desk.basic.READ" ]
        } ],
        "x-audience" : [ "external-public" ]
      },
      "patch" : {
        "tags" : [ "User" ],
        "summary" : "Update User Details",
        "description" : "This API helps update the details of a particular help center user. ",
        "operationId" : "updateUserDetails",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "helpCenterId",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "ID of the help center from which the user must be updated"
        }, {
          "name" : "userId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/updateUserJson"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/userDetailViewJson"
          },
          "422" : {
            "$ref" : "./Common.json#/components/responses/invalidDataErrorResponse"
          },
          "500" : {
            "$ref" : "./Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "./Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.contacts.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/users/{userId}/groups/associate" : {
      "post" : {
        "tags" : [ "User" ],
        "summary" : "Associate Groups To Users",
        "description" : "This API adds a user to the groups specified.",
        "operationId" : "associateGroupsToUsers",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "helpCenterId",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "ID of the help center from which the groups must be validated"
        }, {
          "name" : "userId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/userGroupInputJson"
        },
        "responses" : {
          "422" : {
            "$ref" : "./Common.json#/components/responses/invalidDataErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/massActionListViewResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.contacts.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/users/{userId}/labels" : {
      "get" : {
        "tags" : [ "User" ],
        "summary" : "Get User Labels",
        "description" : "This API lists a particular number of labels associated with a user, based on the limit defined.",
        "operationId" : "getUserLabels",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "isPrimary",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "boolean" ]
          },
          "style" : "form",
          "explode" : true,
          "description" : "Key that filters the primary label assigned to the user"
        }, {
          "name" : "from",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "integer" ],
            "format" : "int32",
            "minimum" : 1,
            "default" : 1
          },
          "style" : "form",
          "explode" : true,
          "description" : "Index number, starting from which the labels must be fetched. The default value is 1"
        }, {
          "name" : "limit",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "integer" ],
            "format" : "int32",
            "minimum" : 1,
            "maximum" : 50,
            "default" : 50
          },
          "style" : "form",
          "explode" : true,
          "description" : "Number of labels to list. The default value and the maximum value allowed is 50"
        }, {
          "name" : "sortBy",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string" ],
            "pattern" : "-?(assignedTime)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "Key that sorts the list of labels by a particular attribute: -(@assignedTime@)"
        }, {
          "name" : "searchBy",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string" ],
            "pattern" : "[0-9a-zA-Z_\\-\\&\\.\\$\\@\\^\\(\\)\\{\\}\\~\\=\\-\\|\\*\\+\\?\\[\\]\\,\\:\\\"\\'\\/\\!\\P{InBasicLatin}\\s]+",
            "x-regex-name" : "cleartextampersand"
          },
          "style" : "form",
          "explode" : true,
          "description" : "Search keyword to use for finding a particular user. The keyword must contain at least two characters."
        }, {
          "name" : "helpCenterId",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "ID of the help center from which the labels must be fetched"
        }, {
          "name" : "userId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/userLabelJson"
          },
          "422" : {
            "$ref" : "./Common.json#/components/responses/invalidDataErrorResponse"
          },
          "500" : {
            "$ref" : "./Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "./Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.contacts.READ", "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/users/{userId}/labels/remove" : {
      "post" : {
        "tags" : [ "User" ],
        "summary" : "Remove Labels From User",
        "description" : "This API removes the labels you specify from a particular user.",
        "operationId" : "removeLabelsFromUser",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "helpCenterId",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "ID of the help center from which the labels must be removed"
        }, {
          "name" : "userId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "./Label.json#/components/requestBodies/labelIdsJson"
        },
        "responses" : {
          "422" : {
            "$ref" : "./Common.json#/components/responses/invalidDataErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/massActionListViewResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.contacts.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/users/{userId}/groups/dissociate" : {
      "post" : {
        "tags" : [ "User" ],
        "summary" : "Delete Groups From Users",
        "description" : "This API removes a user from the groups specified.",
        "operationId" : "deleteGroupsFromUsers",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "helpCenterId",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "ID of the help center from which the groups must be removed"
        }, {
          "name" : "userId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "./HelpcenterGroups.json#/components/requestBodies/groupIds"
        },
        "responses" : {
          "422" : {
            "$ref" : "./Common.json#/components/responses/invalidDataErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/massActionListViewResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.contacts.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/users/{userId}/anonymize" : {
      "post" : {
        "tags" : [ "User" ],
        "summary" : "Delete End User",
        "description" : "This API permanently deletes all identifying information about a user from your help center.",
        "operationId" : "deleteEndUser",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "userId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/anonymizeInpJson"
        },
        "responses" : {
          "404" : {
            "$ref" : "./Common.json#/components/responses/urlNotFoundErrorResponse"
          },
          "422" : {
            "$ref" : "./Common.json#/components/responses/invalidDataErrorResponse"
          },
          "500" : {
            "$ref" : "./Common.json#/components/responses/internalErrorResponse"
          },
          "204" : {
            "$ref" : "./Common.json#/components/responses/emptyResponse"
          },
          "403" : {
            "$ref" : "./Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.contacts.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/users" : {
      "get" : {
        "tags" : [ "User" ],
        "summary" : "Get Users",
        "description" : "This API lists a particular number of help center users, based on the limit defined. It also helps you search for specific users.",
        "operationId" : "getUsers",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "from",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "integer" ],
            "format" : "int32",
            "minimum" : 1,
            "default" : 1
          },
          "style" : "form",
          "explode" : true,
          "description" : "Index number, starting from which the users must be fetched. The default value is 1"
        }, {
          "name" : "limit",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "integer" ],
            "format" : "int32",
            "minimum" : 1,
            "maximum" : 50,
            "default" : 50
          },
          "style" : "form",
          "explode" : true,
          "description" : "Number of users to be listed. The default and the maximum allowed value is 50"
        }, {
          "name" : "searchBy",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string" ],
            "pattern" : "[0-9a-zA-Z_\\-\\&\\.\\$\\@\\^\\(\\)\\{\\}\\~\\=\\-\\|\\*\\+\\?\\[\\]\\,\\:\\\"\\'\\/\\!\\P{InBasicLatin}\\s]+",
            "x-regex-name" : "cleartextampersand"
          },
          "style" : "form",
          "explode" : true,
          "description" : "Search keyword to find a particular user. Note: The keyword must contain at least two characters"
        }, {
          "name" : "sortBy",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string" ],
            "pattern" : "-?(email|modifiedTime)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "Key that sorts the list of users by a particular attribute: -(@email@ or @modifiedTime@)"
        }, {
          "name" : "status",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string" ],
            "enum" : [ "ACTIVE", "DISABLED", "DELETED", "ALL" ]
          },
          "style" : "form",
          "explode" : true,
          "description" : "Activation status of the users to list"
        }, {
          "name" : "helpCenterId",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "ID of the help center from which the users must be fetched"
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        }, {
          "name" : "include",
          "in" : "query",
          "description" : "Additional information related to the user. Value allowed is @count@.",
          "required" : false,
          "style" : "simple",
          "explode" : true,
          "schema" : {
            "type" : [ "null", "array" ],
            "description" : "Additional information related to the user. Value allowed is @count@.",
            "items" : {
              "type" : [ "string", "null" ],
              "enum" : [ "count" ],
              "maxLength" : 100,
              "minLength" : 0
            },
            "uniqueItems" : true
          }
        }, {
          "name" : "lastActivityStartTime",
          "in" : "query",
          "description" : "Starting time of the time range in which the comments should have been created. The value must be expressed according to the GMT time zone.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "null" ],
            "description" : "Starting time of the time range in which the comments should have been created. The value must be expressed according to the GMT time zone.",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "^(202[0-9]|20[3-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\\.[0-9]{3})?Z$"
          }
        }, {
          "name" : "lastActivityEndTime",
          "in" : "query",
          "description" : "Starting time of the time range in which the comments should have been created. The value must be expressed according to the GMT time zone.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "null" ],
            "description" : "Starting time of the time range in which the comments should have been created. The value must be expressed according to the GMT time zone.",
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "^(202[0-9]|20[3-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\\.[0-9]{3})?Z$"
          }
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/getUsersResponse"
          },
          "422" : {
            "$ref" : "./Common.json#/components/responses/invalidDataErrorResponse"
          },
          "500" : {
            "$ref" : "./Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "./Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.contacts.READ", "Desk.settings.READ", "Desk.basic.READ", "Desk.search.READ" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/users/{userId}/labels/assign" : {
      "post" : {
        "tags" : [ "User" ],
        "summary" : "Assign Labels To User",
        "description" : "This API assigns the labels you specify to a particular user. ",
        "operationId" : "assignLabelsToUser",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "helpCenterId",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "ID of the help center from which the labels must be validated"
        }, {
          "name" : "userId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/userLabelInputJson"
        },
        "responses" : {
          "422" : {
            "$ref" : "./Common.json#/components/responses/invalidDataErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/massActionListViewResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.contacts.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/users/{userId}/groups" : {
      "get" : {
        "tags" : [ "User" ],
        "summary" : "Get User Groups",
        "description" : "This API lists a particular number of user groups in a help center, based on the limit defined.",
        "operationId" : "getUserGroups",
        "x-mcp-ready" : true,
        "parameters" : [ {
          "name" : "from",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "integer" ],
            "format" : "int32",
            "minimum" : 1,
            "default" : 1
          },
          "style" : "form",
          "explode" : true,
          "description" : "Index number, starting from which the groups must be fetched. The default value is 1"
        }, {
          "name" : "limit",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "integer" ],
            "format" : "int32",
            "minimum" : 1,
            "maximum" : 50,
            "default" : 50
          },
          "style" : "form",
          "explode" : true,
          "description" : "Number of groups to list. The default value and the maximum value allowed is 50"
        }, {
          "name" : "searchBy",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string" ],
            "pattern" : "[0-9a-zA-Z_\\-\\&\\.\\$\\@\\^\\(\\)\\{\\}\\~\\=\\-\\|\\*\\+\\?\\[\\]\\,\\:\\\"\\'\\/\\!\\P{InBasicLatin}\\s]+",
            "x-regex-name" : "cleartextampersand"
          },
          "style" : "form",
          "explode" : true,
          "description" : "Search keyword to use for finding a particular user. The keyword must contain at least two characters."
        }, {
          "name" : "sortBy",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string" ],
            "pattern" : "-?((addedTime))"
          },
          "style" : "form",
          "explode" : true,
          "description" : "Key that sorts the list of user groups by a particular attribute: -(@addedTime@)"
        }, {
          "name" : "helpCenterId",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : [ "string", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "style" : "form",
          "explode" : true,
          "description" : "ID of the help center from which the groups must be fetched"
        }, {
          "name" : "userId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        }, {
          "$ref" : "./Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/userGroupJson"
          },
          "422" : {
            "$ref" : "./Common.json#/components/responses/invalidDataErrorResponse"
          },
          "500" : {
            "$ref" : "./Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "./Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.contacts.READ", "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    },
    "/api/v1/portalUsers/{userId}/removeUser" : {
      "post" : {
        "tags" : [ "User" ],
        "summary" : "Remove Portal User",
        "description" : "Removes a portal user from the help center.",
        "operationId" : "removePortalUser",
        "parameters" : [ {
          "name" : "userId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        } ],
        "responses" : {
          "204" : {
            "$ref" : "./Common.json#/components/responses/emptyResponse"
          },
          "404" : {
            "$ref" : "./Common.json#/components/responses/urlNotFoundErrorResponse"
          },
          "403" : {
            "$ref" : "./Common.json#/components/responses/forbiddenErrorResponse"
          },
          "500" : {
            "$ref" : "./Common.json#/components/responses/internalErrorResponse"
          }
        },
        "security" : [ {
          "iam-oauth2-schema" : [ "Desk.settings.DELETE", "Desk.basic.DELETE" ]
        } ],
        "x-audience" : [ "external-public" ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "massActionErrorResponse" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "errorCode" : {
            "type" : [ "string", "null" ],
            "enum" : [ "UNPROCESSABLE_ENTITY", "UNAUTHORIZED", "FORBIDDEN", "INVALID_DATA", "SCHEDULED", "SUCCESS" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "error" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+"
          },
          "httpCode" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int32",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "error", "errorCode", "httpCode" ]
      },
      "massActionJsonResponse" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "success" : {
            "type" : [ "boolean", "null" ]
          },
          "id" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "errors" : {
            "$ref" : "#/components/schemas/massActionErrorResponse"
          }
        },
        "required" : [ "errors", "id", "success" ]
      },
      "massActionJsonArray" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "#/components/schemas/massActionJsonResponse"
        }
      },
      "userDefaultJson" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "photoUrl" : {
            "type" : [ "string", "null" ],
            "maxLength" : 200,
            "minLength" : 0,
            "pattern" : "(^(ht|f)tp(s?)\\://[-.\\w]*(/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'/\\\\+=&%\\$#_@]*)?$)"
          },
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "id" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "id", "name", "photoUrl" ]
      },
      "userMetaJson" : {
        "additionalProperties" : false,
        "allOf" : [ {
          "$ref" : "#/components/schemas/userDefaultJson"
        }, {
          "type" : [ "object", "null" ],
          "properties" : {
            "emailAddress" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "^[a-zA-Z0-9\\_]([a-zA-Z0-9\\_\\+\\-\\.\\'&]*)@(?=.{4,256}$)(([a-zA-Z0-9]+)(([\\-\\_]*[a-zA-Z0-9])*)[\\.])+[a-zA-Z]{2,22}$"
            },
            "userType" : {
              "type" : [ "string", "null" ],
              "enum" : [ "ENDUSER", "SUPPORTREP" ]
            },
            "status" : {
              "type" : [ "string", "null" ],
              "enum" : [ "ACTIVE", "DISABLED", "DELETED" ]
            }
          },
          "required" : [ "emailAddress", "status", "userType" ],
          "additionalProperties" : false
        }, {
          "$ref" : "./User.json#/components/schemas/userDefaultJson"
        }, {
          "type" : [ "null", "object" ],
          "properties" : {
            "emailAddress" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "^[a-zA-Z0-9\\_]([a-zA-Z0-9\\_\\+\\-\\.\\'&]*)@(?=.{4,256}$)(([a-zA-Z0-9]+)(([\\-\\_]*[a-zA-Z0-9])*)[\\.])+[a-zA-Z]{2,22}$"
            },
            "userType" : {
              "type" : [ "string", "null" ],
              "enum" : [ "ENDUSER", "SUPPORTREP" ],
              "maxLength" : 100,
              "minLength" : 0
            },
            "status" : {
              "type" : [ "string", "null" ],
              "enum" : [ "ACTIVE", "DISABLED", "DELETED" ],
              "maxLength" : 100,
              "minLength" : 0
            }
          },
          "required" : [ "emailAddress", "status", "userType" ]
        } ]
      },
      "userEmailObj" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "emailAddress" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "^[a-zA-Z0-9\\_]([a-zA-Z0-9\\_\\+\\-\\.\\'&]*)@(?=.{4,256}$)(([a-zA-Z0-9]+)(([\\-\\_]*[a-zA-Z0-9])*)[\\.])+[a-zA-Z]{2,22}$"
          },
          "isVerified" : {
            "type" : [ "boolean", "null" ]
          },
          "isPrimary" : {
            "type" : [ "boolean", "null" ]
          }
        },
        "required" : [ "emailAddress", "isPrimary", "isVerified" ]
      },
      "userEmailObjArray" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "#/components/schemas/userEmailObj"
        }
      },
      "userGroupInputJsonObj" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "id" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "id" ]
      },
      "userGroupInputJsonArr" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "#/components/schemas/userGroupInputJsonObj"
        }
      },
      "userLabelJsonObj" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "./Label.json#/components/schemas/userLabelMetaResponse"
        }
      },
      "userDetailJson" : {
        "additionalProperties" : false,
        "allOf" : [ {
          "$ref" : "#/components/schemas/userDefaultJson"
        }, {
          "type" : [ "object", "null" ],
          "properties" : {
            "lastAccessedTime" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
            },
            "emailAddress" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "^[a-zA-Z0-9\\_]([a-zA-Z0-9\\_\\+\\-\\.\\'&]*)@(?=.{4,256}$)(([a-zA-Z0-9]+)(([\\-\\_]*[a-zA-Z0-9])*)[\\.])+[a-zA-Z]{2,22}$"
            },
            "userType" : {
              "type" : [ "string", "null" ],
              "enum" : [ "ENDUSER", "SUPPORTREP" ]
            },
            "label" : {
              "$ref" : "./Label.json#/components/schemas/labelMetaResponse"
            },
            "status" : {
              "type" : [ "string", "null" ],
              "enum" : [ "ACTIVE", "DISABLED", "DELETED" ]
            }
          },
          "required" : [ "emailAddress", "label", "lastAccessedTime", "status", "userType" ],
          "additionalProperties" : false
        }, {
          "$ref" : "./User.json#/components/schemas/userDefaultJson"
        }, {
          "type" : [ "null", "object" ],
          "properties" : {
            "lastAccessedTime" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
            },
            "emailAddress" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "^[a-zA-Z0-9\\_]([a-zA-Z0-9\\_\\+\\-\\.\\'&]*)@(?=.{4,256}$)(([a-zA-Z0-9]+)(([\\-\\_]*[a-zA-Z0-9])*)[\\.])+[a-zA-Z]{2,22}$"
            },
            "userType" : {
              "type" : [ "string", "null" ],
              "enum" : [ "ENDUSER", "SUPPORTREP" ],
              "maxLength" : 100,
              "minLength" : 0
            },
            "label" : {
              "$ref" : "./Label.json#/components/schemas/labelMetaResponse"
            },
            "status" : {
              "type" : [ "string", "null" ],
              "enum" : [ "ACTIVE", "DISABLED", "DELETED" ],
              "maxLength" : 100,
              "minLength" : 0
            }
          },
          "required" : [ "emailAddress", "label", "lastAccessedTime", "status", "userType" ]
        } ]
      },
      "data" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "#/components/schemas/userDetailJson"
        }
      },
      "userLabelInputJsonObj" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "isPrimary" : {
            "type" : [ "boolean", "null" ]
          },
          "id" : {
            "type" : [ "string", "integer", "null" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "id", "isPrimary" ]
      },
      "userLabelInputJsonArr" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "#/components/schemas/userLabelInputJsonObj"
        }
      },
      "userGroupJsonObj" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "./HelpcenterGroups.json#/components/schemas/groupMetaResponse"
        }
      }
    },
    "responses" : {
      "massActionListViewResponse" : {
        "description" : "massActionListViewResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "results" : {
                  "$ref" : "#/components/schemas/massActionJsonArray"
                }
              },
              "required" : [ "results" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "results" : [ {
                    "success" : true,
                    "id" : "24073000002958013",
                    "errors" : null
                  }, {
                    "success" : true,
                    "id" : "24073000002958023",
                    "errors" : null
                  }, {
                    "success" : false,
                    "id" : "24073000002152013",
                    "errors" : {
                      "errorCode" : "FORBIDDEN",
                      "httpCode" : 403,
                      "error" : "Restricted"
                    }
                  } ]
                }
              }
            }
          }
        }
      },
      "userDetailViewJson" : {
        "description" : "userDetailViewJson template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "additionalProperties" : false,
              "allOf" : [ {
                "$ref" : "#/components/schemas/userDefaultJson"
              }, {
                "type" : [ "object", "null" ],
                "properties" : {
                  "lastAccessedTime" : {
                    "type" : [ "string", "null" ],
                    "maxLength" : 100,
                    "minLength" : 0,
                    "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
                  },
                  "contactId" : {
                    "type" : [ "string", "integer", "null" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)"
                  },
                  "userType" : {
                    "type" : [ "string", "null" ],
                    "enum" : [ "ENDUSER", "SUPPORTREP" ]
                  },
                  "label" : {
                    "$ref" : "./Label.json#/components/schemas/labelMetaResponse"
                  },
                  "email" : {
                    "$ref" : "#/components/schemas/userEmailObjArray"
                  },
                  "status" : {
                    "type" : [ "string", "null" ],
                    "enum" : [ "ACTIVE", "DISABLED", "DELETED" ]
                  }
                },
                "required" : [ "contactId", "email", "label", "lastAccessedTime", "status", "userType" ],
                "additionalProperties" : false
              }, {
                "$ref" : "./User.json#/components/schemas/userDefaultJson"
              }, {
                "type" : [ "null", "object" ],
                "properties" : {
                  "lastAccessedTime" : {
                    "type" : [ "string", "null" ],
                    "maxLength" : 100,
                    "minLength" : 0,
                    "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
                  },
                  "contactId" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)"
                  },
                  "userType" : {
                    "type" : [ "string", "null" ],
                    "enum" : [ "ENDUSER", "SUPPORTREP" ],
                    "maxLength" : 100,
                    "minLength" : 0
                  },
                  "label" : {
                    "$ref" : "./Label.json#/components/schemas/labelMetaResponse"
                  },
                  "email" : {
                    "$ref" : "./User.json#/components/schemas/userEmailObjArray"
                  },
                  "status" : {
                    "type" : [ "string", "null" ],
                    "enum" : [ "ACTIVE", "DISABLED", "DELETED" ],
                    "maxLength" : 100,
                    "minLength" : 0
                  }
                },
                "required" : [ "contactId", "email", "label", "lastAccessedTime", "status", "userType" ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "lastAccessedTime" : "2021-06-11T06:21:32.000Z",
                  "photoURL" : "https://desk.example.com/portal/api/portalUser/17883000000094001/photo",
                  "contactId" : "3313135931139",
                  "name" : "Developer",
                  "id" : "310975130121",
                  "label" : {
                    "preferences" : {
                      "shape" : "RECTANGLE",
                      "bgColor" : "#39B54A",
                      "textColor" : "#FFFFFF"
                    },
                    "name" : "Lock Label",
                    "id" : "24073000002823026",
                    "logoUrl" : null
                  },
                  "type" : [ "ENDUSER" ],
                  "email" : [ {
                    "emailAddress" : "zylcare@zylker.com",
                    "isVerified" : "false",
                    "isPrimary" : "true"
                  } ],
                  "status" : "ACTIVE"
                }
              }
            }
          }
        }
      },
      "userLabelJson" : {
        "description" : "userLabelJson template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "data" : {
                  "$ref" : "#/components/schemas/userLabelJsonObj"
                }
              },
              "required" : [ "data" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "preferences" : {
                      "shape" : "ROUNDED",
                      "bgColor" : "#5787E0",
                      "textColor" : "#FFFFFF"
                    },
                    "isPrimary" : false,
                    "name" : "Prime Customer",
                    "id" : "24073000002958013",
                    "helpCenterId" : "24073000002886005",
                    "logoUrl" : null,
                    "assignedTime" : "2020-04-06T05:55:13.000Z"
                  }, {
                    "preferences" : {
                      "shape" : "RECTANGLE",
                      "bgColor" : "#39B54A",
                      "textColor" : "#FFFFFF"
                    },
                    "isPrimary" : false,
                    "name" : "Zoho One",
                    "id" : "24073000002958023",
                    "helpCenterId" : "24073000002886005",
                    "logoUrl" : null,
                    "assignedTime" : "2020-04-06T05:55:13.000Z"
                  }, {
                    "preferences" : {
                      "shape" : "RECTANGLE",
                      "bgColor" : "#CE6785",
                      "textColor" : "#FFFFFF"
                    },
                    "isPrimary" : false,
                    "name" : "MVP",
                    "id" : "24073000002958029",
                    "helpCenterId" : "24073000002886005",
                    "logoUrl" : null,
                    "assignedTime" : "2020-04-06T05:55:13.000Z"
                  } ]
                }
              }
            }
          }
        }
      },
      "getUsersResponse" : {
        "description" : "getUsersResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "allOf" : [ {
                "type" : [ "object" ],
                "properties" : {
                  "data" : {
                    "type" : [ "array" ],
                    "items" : {
                      "type" : [ "object" ],
                      "properties" : {
                        "count" : {
                          "type" : [ "string", "integer", "null" ],
                          "format" : "int32",
                          "pattern" : "([0-9]+)"
                        }
                      }
                    }
                  }
                }
              }, {
                "anyOf" : [ {
                  "type" : [ "object", "null" ],
                  "additionalProperties" : false,
                  "properties" : {
                    "data" : {
                      "$ref" : "#/components/schemas/data"
                    }
                  },
                  "required" : [ "data" ]
                }, {
                  "type" : [ "object", "null" ],
                  "additionalProperties" : false,
                  "properties" : {
                    "data" : {
                      "$ref" : "#/components/schemas/data"
                    },
                    "count" : {
                      "type" : [ "string", "integer", "null" ],
                      "format" : "int32",
                      "pattern" : "([0-9]+)"
                    }
                  },
                  "required" : [ "data", "count" ]
                } ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "lastAccessedTime" : "2021-06-11T06:21:32.000Z",
                    "photoURL" : "https://desk.example.com/portal/api/portalUser/17883000000094001/photo",
                    "emailAddress" : "carol@zylker.com",
                    "name" : "Developer",
                    "id" : "310975130121",
                    "label" : {
                      "preferences" : {
                        "shape" : "RECTANGLE",
                        "bgColor" : "#39B54A",
                        "textColor" : "#FFFFFF"
                      },
                      "name" : "Lock Label",
                      "id" : "24073000002823026",
                      "logoUrl" : null
                    },
                    "type" : [ "ENDUSER" ],
                    "status" : "ACTIVE"
                  }, {
                    "lastAccessedTime" : "2021-06-11T06:21:32.000Z",
                    "photoURL" : "https://desk.example.com/portal/api/portalUser/17883000000094001/photo",
                    "emailAddress" : "carol@zylker.com",
                    "name" : "Developer",
                    "id" : "310975130121",
                    "label" : {
                      "preferences" : {
                        "shape" : "RECTANGLE",
                        "bgColor" : "#39B54A",
                        "textColor" : "#FFFFFF"
                      },
                      "name" : "Lock Label",
                      "id" : "24073000002823026",
                      "logoUrl" : null
                    },
                    "type" : "ENDUSER",
                    "status" : "ACTIVE"
                  } ],
                  "count" : "1"
                }
              }
            }
          }
        }
      },
      "userGroupJson" : {
        "description" : "userGroupJson template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "data" : {
                  "$ref" : "#/components/schemas/userGroupJsonObj"
                }
              },
              "required" : [ "data" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "addedTime" : "2020-04-06T04:50:50.000Z",
                    "name" : "Zoho CRM Partners",
                    "id" : "24073000002957057",
                    "helpCenterId" : "24073000002733221",
                    "logoUrl" : null,
                    "status" : "ACTIVE"
                  }, {
                    "addedTime" : "2020-04-06T04:50:30.000Z",
                    "name" : "Zoho Desk Partners",
                    "id" : "24073000002957051",
                    "helpCenterId" : "24073000002733221",
                    "logoUrl" : "https://desk.example.com/portal/api/publicImages/24073000002959001?portalId=b363e6f8e029247a38a55e49806bf1f683801f9cd92870bf7cc50d48844902f0",
                    "status" : "ACTIVE"
                  }, {
                    "addedTime" : "2020-04-06T04:50:14.000Z",
                    "name" : "Zoho One Prime Customers",
                    "id" : "24073000002957045",
                    "helpCenterId" : "24073000002733221",
                    "logoUrl" : null,
                    "status" : "ACTIVE"
                  } ]
                }
              }
            }
          }
        }
      }
    },
    "requestBodies" : {
      "userGroupInputJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "groups" : {
                  "$ref" : "#/components/schemas/userGroupInputJsonArr"
                }
              },
              "required" : [ "groups" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "groups" : [ {
                    "id" : "24073000002723212"
                  }, {
                    "id" : "24073000002732252"
                  }, {
                    "id" : "24073000002957051"
                  }, {
                    "id" : "24073000002793019"
                  } ]
                }
              }
            }
          }
        }
      },
      "anonymizeInpJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "anonymizedName" : {
                  "type" : [ "string", "null" ],
                  "description" : "Display name of the user in tickets and community topics after anonymization",
                  "maxLength" : 100,
                  "pattern" : "[A-Za-z0-9~@$%_\\!\\^\\[\\]\\{\\},#*:`.'\"&\\+\\?\\-\\\\\\/\\|\\P{InBasicLatin}\\s]+",
                  "minLength" : 0
                }
              }
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "anonymizedName" : "Guest User 001"
                }
              }
            }
          }
        }
      },
      "userLabelInputJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "labels" : {
                  "$ref" : "#/components/schemas/userLabelInputJsonArr"
                }
              },
              "required" : [ "labels" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "labels" : [ {
                    "isPrimary" : "false",
                    "id" : "24073000002958013"
                  }, {
                    "isPrimary" : "true",
                    "id" : "24073000002152013"
                  }, {
                    "isPrimary" : "false",
                    "id" : "24073000002958023"
                  } ]
                }
              }
            }
          }
        }
      },
      "updateUserJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "email" : {
                  "type" : [ "array", "null" ],
                  "items" : {
                    "type" : [ "object", "null" ],
                    "additionalProperties" : false,
                    "maxProperties" : 2,
                    "minProperties" : 2,
                    "properties" : {
                      "emailAddress" : {
                        "type" : [ "string", "null" ],
                        "maxLength" : 100,
                        "minLength" : 0,
                        "pattern" : "^[a-zA-Z0-9\\_]([a-zA-Z0-9\\_\\+\\-\\.\\'&]*)@(?=.{4,256}$)(([a-zA-Z0-9]+)(([\\-\\_]*[a-zA-Z0-9])*)[\\.])+[a-zA-Z]{2,22}$"
                      },
                      "isPrimary" : {
                        "type" : [ "boolean", "null" ]
                      }
                    },
                    "required" : [ "emailAddress", "isPrimary" ]
                  },
                  "maxItems" : 1,
                  "minItems" : 1,
                  "uniqueItems" : false
                },
                "status" : {
                  "type" : [ "string", "null" ],
                  "description" : "Activation status of the user. Values supported are @ACTIVE@ and @DISABLED@.",
                  "enum" : [ "ACTIVE", "DISABLED", "DELETED" ],
                  "maxLength" : 100,
                  "minLength" : 0
                }
              }
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "email" : [ {
                    "emailAddress" : "zylcare@zylker.com",
                    "isPrimary" : "true"
                  } ],
                  "status" : "ACTIVE"
                }
              }
            }
          }
        }
      }
    },
    "securitySchemes" : {
      "cookie-auth" : {
        "$ref" : "./Common.json#/components/securitySchemes/cookie-auth"
      },
      "org-oauth" : {
        "$ref" : "./Common.json#/components/securitySchemes/org-oauth"
      },
      "jwt-oauth" : {
        "$ref" : "./Common.json#/components/securitySchemes/jwt-oauth"
      },
      "iam-oauth2-schema" : {
        "$ref" : "./Common.json#/components/securitySchemes/iam-oauth2-schema"
      }
    }
  },
  "x-entity" : "User"
}